CREATE USER 'Junior'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Juka9999';
GRANT ALL PRIVILEGES ON *.* TO 'Junior'@'localhost' WITH GRANT OPTION;

#SHOW DATABASES;
#CREATE DATABASE escola_express;
USE escola_express;

DROP TABLE IF EXISTS USUARIO_ATIVIDADE;
DROP TABLE IF EXISTS ATIVIDADE;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR (40), 
  email VARCHAR (100) UNIQUE,
  password VARCHAR(128) NOT NULL
);

CREATE TABLE ATIVIDADE (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR (100), 
  descricao VARCHAR (100),
  data DATE
);

CREATE TABLE USUARIO_ATIVIDADE (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_usuario INTEGER,
  id_atividade INTEGER,
  data DATE,
  nota DOUBLE,
  FOREIGN KEY(id_usuario) REFERENCES USUARIO(id),
  FOREIGN KEY(id_atividade) REFERENCES ATIVIDADE(id)
);

INSERT INTO USUARIO(nome, email, password) VALUES ("Joaquim", "caetano@gmail.com", "123456"), ("Junior", "Junior@gmail.com", "123456");
INSERT INTO ATIVIDADE(titulo, descricao, data) VALUE ("EXPRESS", "Criar banco no MYSQL", "2024-03-20");
INSERT INTO USUARIO_ATIVIDADE(id_usuario, id_atividade, data, nota) VALUE (1, 1, "2024-03-24", 10);

SELECT * FROM USUARIO;
